### ISSUE TITLE
iOS 14 适配问题

### ISSUE THREAD

**Issue by a1003072244** [hackxhj/YHPhotoBrowser#4]
图片显示有问题

**Comment by yangwubo0800** [comment]
遇到同样的问题，以前ios低版本能正常预览，现在会黑屏。

**Comment by yangwubo0800** [comment]
https://github.com/indulgeIn/YBImageBrowser/issues/327

YYImage 使用下面这个仓库就行了
pod 'YYImage', :git => 'https://github.com/QiuYeHong90/YYImage.git'

这个仓库已经修正了这个兼容问题，亲测有效， 请作者更新同步修改，方便他人应用你的这个库，谢谢。

**Comment by hackxhj** [comment]
> [indulgeIn/YBImageBrowser#327](https://github.com/indulgeIn/YBImageBrowser/issues/327)
> 
> YYImage 使用下面这个仓库就行了
> pod 'YYImage', :git => 'https://github.com/QiuYeHong90/YYImage.git'
> 
> 这个仓库已经修正了这个兼容问题，亲测有效， 请作者更新同步修改，方便他人应用你的这个库，谢谢。

感谢 已经更新
